services:
  wordpress:
    build: .
    container_name: wpvn-wordpress
    ports:
      - "8000:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/wp-visitor-notify
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8000');
        define('WP_SITEURL', 'http://localhost:8000');
      WORDPRESS_TABLE_PREFIX: wp_
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - wpvn-network

  db:
    image: mysql:5.7
    container_name: wpvn-database
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    networks:
      - wpvn-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: wpvn-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      UPLOAD_LIMIT: 64M
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    networks:
      - wpvn-network

networks:
  wpvn-network:
    driver: bridge

volumes:
  wordpress_data:
  db_data:
